name: JSON Schema CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SCHEMA_DIRS: |
    au.org.access-nri/model/output/file-metadata/2-0-0
    au.org.access-nri/model/output/file-metadata/2-1-0
  # TEST_DIRS need to have matching SCHEMA_DIRS in the same order
  TEST_DIRS: |
    tests/2-0-0
    tests/2-1-0

jobs:
  schema-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the Sourcemeta JSON Schema CLI
        uses: sourcemeta/jsonschema@v14.14.2

      - name: Check schemas against their metaschemas
        run: jsonschema metaschema --verbose $SCHEMA_DIRS

      - name: Check schemas are formatted
        run: jsonschema fmt --check --verbose $SCHEMA_DIRS

      - name: Lint schemas
        run: |
          jsonschema lint --verbose \
            --exclude enum_with_type \
            --exclude description_trailing_period \
            --exclude top_level_examples \
            $SCHEMA_DIRS

      - name: Run test suite
        run: |
          # Need to iterate through each pair of DIRS since there will be name
          # collisions with different versions of the same schema 
          for i in "${!TEST_DIRS[@]}"; do
            TEST_DIR=${TEST_DIRS[i]}
            SCHEMA_DIR=${SCHEMA_DIRS[i]}
            jsonschema test --verbose $TEST_DIR --resolve $SCHEMA_DIR
          done
